id: P007838
initial_creation_type: ocr
source_metadata:
  id: bdr:W3PD405
  title: མཛོད་ལྷ་འགྲེལ།
  author: ''
  volumes:
    dbc3f3610ce7489f8975b799c71112bf:
      image_group_id: I2PD18030
      title: ''
      volume_number: 1
      total_pages: 244
    3736cbefcdb946ad81bb1f50770ee202:
      image_group_id: I2PD18031
      title: ''
      volume_number: 2
      total_pages: 384
ebook_metadata:
  title: མཛོད་ལྷ་འགྲེལ།
  author: ''
  sku: P007838
  cover: cover.jpg
  layers:
  - pagination
