id: IDA4A25EE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T14:24:35+00:00'
last_modified: '2022-06-09T06:25:37.596282+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3PD405
  title: མཛོད་ལྷ་འགྲེལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    8E2B:
      image_group_id: I2PD18030
      title: Volume 1 of mdzod lha 'grel/
      total_pages: 244
      order: 1
      base_file: 8E2B.txt
    '5658':
      image_group_id: I2PD18031
      title: Volume 2 of mdzod lha 'grel/
      total_pages: 384
      order: 2
      base_file: 5658.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
